"""baseline schema

Revision ID: 023059e59454
Revises: 
Create Date: 2026-07-05 07:22:24.431139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '023059e59454'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('online', 'draining', 'stopped', 'dead', name='worker_status'), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workers_heartbeat', 'workers', ['last_heartbeat_at'], unique=False)
    op.create_index('ix_workers_status', 'workers', ['status'], unique=False)
    op.create_table('org_members',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='org_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'org_id', name='uq_org_member')
    )
    op.create_index(op.f('ix_org_members_org_id'), 'org_members', ['org_id'], unique=False)
    op.create_index(op.f('ix_org_members_user_id'), 'org_members', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('org_id', 'name', name='uq_project_name')
    )
    op.create_index(op.f('ix_projects_org_id'), 'projects', ['org_id'], unique=False)
    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.BigInteger(), nullable=False),
    sa.Column('in_flight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_heartbeats_worker_created', 'worker_heartbeats', ['worker_id', 'created_at'], unique=False)
    op.create_table('retry_policies',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('strategy', sa.Enum('fixed', 'linear', 'exponential', name='retry_strategy'), nullable=False),
    sa.Column('base_delay_s', sa.Float(), nullable=False),
    sa.Column('max_delay_s', sa.Float(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('jitter', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_delay_s >= 0', name='ck_retry_base_delay'),
    sa.CheckConstraint('max_attempts >= 1', name='ck_retry_max_attempts'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retry_policies_project_id'), 'retry_policies', ['project_id'], unique=False)
    op.create_table('queues',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('concurrency_limit', sa.Integer(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('retry_policy_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('concurrency_limit >= 1', name='ck_queue_concurrency'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retry_policy_id'], ['retry_policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_queue_name')
    )
    op.create_index(op.f('ix_queues_project_id'), 'queues', ['project_id'], unique=False)
    op.create_index(op.f('ix_queues_retry_policy_id'), 'queues', ['retry_policy_id'], unique=False)
    op.create_table('jobs',
    sa.Column('queue_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'queued', 'claimed', 'running', 'completed', 'failed', 'dead', 'cancelled', name='job_status'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('worker_id', sa.BigInteger(), nullable=True),
    sa.Column('retry_policy_id', sa.BigInteger(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retry_policy_id'], ['retry_policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_claim', 'jobs', ['queue_id', sa.literal_column('priority DESC'), 'run_at', 'id'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_index('ix_jobs_idempotency', 'jobs', ['project_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_index('ix_jobs_project_created', 'jobs', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_jobs_queue_status', 'jobs', ['queue_id', 'status'], unique=False)
    op.create_index('ix_jobs_scheduled_run_at', 'jobs', ['run_at'], unique=False, postgresql_where=sa.text("status = 'scheduled'"))
    op.create_index(op.f('ix_jobs_worker_id'), 'jobs', ['worker_id'], unique=False)
    op.create_table('scheduled_jobs',
    sa.Column('queue_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('cron_expr', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_jobs_queue_id'), 'scheduled_jobs', ['queue_id'], unique=False)
    op.create_index('ix_scheduled_next_run', 'scheduled_jobs', ['next_run_at'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_table('dead_letter_jobs',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('queue_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('moved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_jobs_job_id'), 'dead_letter_jobs', ['job_id'], unique=False)
    op.create_index('ix_dlq_project_moved', 'dead_letter_jobs', ['project_id', 'moved_at'], unique=False)
    op.create_table('job_executions',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', 'timeout', name='execution_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'attempt', name='uq_execution_attempt')
    )
    op.create_index('ix_executions_job_attempt', 'job_executions', ['job_id', 'attempt'], unique=False)
    op.create_index('ix_executions_started_at', 'job_executions', ['started_at'], unique=False)
    op.create_table('job_logs',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('execution_id', sa.BigInteger(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['job_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_logs_job_created', 'job_logs', ['job_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_logs_job_created', table_name='job_logs')
    op.drop_table('job_logs')
    op.drop_index('ix_executions_started_at', table_name='job_executions')
    op.drop_index('ix_executions_job_attempt', table_name='job_executions')
    op.drop_table('job_executions')
    op.drop_index('ix_dlq_project_moved', table_name='dead_letter_jobs')
    op.drop_index(op.f('ix_dead_letter_jobs_job_id'), table_name='dead_letter_jobs')
    op.drop_table('dead_letter_jobs')
    op.drop_index('ix_scheduled_next_run', table_name='scheduled_jobs', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_scheduled_jobs_queue_id'), table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index(op.f('ix_jobs_worker_id'), table_name='jobs')
    op.drop_index('ix_jobs_scheduled_run_at', table_name='jobs', postgresql_where=sa.text("status = 'scheduled'"))
    op.drop_index('ix_jobs_queue_status', table_name='jobs')
    op.drop_index('ix_jobs_project_created', table_name='jobs')
    op.drop_index('ix_jobs_idempotency', table_name='jobs', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_jobs_claim', table_name='jobs', postgresql_where=sa.text("status = 'queued'"))
    op.drop_table('jobs')
    op.drop_index(op.f('ix_queues_retry_policy_id'), table_name='queues')
    op.drop_index(op.f('ix_queues_project_id'), table_name='queues')
    op.drop_table('queues')
    op.drop_index(op.f('ix_retry_policies_project_id'), table_name='retry_policies')
    op.drop_table('retry_policies')
    op.drop_index('ix_heartbeats_worker_created', table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    op.drop_index(op.f('ix_projects_org_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_org_members_user_id'), table_name='org_members')
    op.drop_index(op.f('ix_org_members_org_id'), table_name='org_members')
    op.drop_table('org_members')
    op.drop_index('ix_workers_status', table_name='workers')
    op.drop_index('ix_workers_heartbeat', table_name='workers')
    op.drop_table('workers')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###

    # Drop the native enum types explicitly. create_table implicitly CREATEs them,
    # but drop_table does not DROP them, which would break a re-upgrade after a
    # full downgrade ("type already exists").
    for enum_name in (
        "job_status",
        "execution_status",
        "worker_status",
        "retry_strategy",
        "org_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
